package org.Disciplinas;


import org.Turma.DiaSemana;
import org.Turma.Horario;
import org.Turma.Turma;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.Turma.DiaSemana.*;


public class CriaDados {
    private Map<String,Disciplina> listaDisciplinas= new HashMap<>();


    public CriaDados(){
        Disciplina algoritmoPratica = new DisciplinaObrigatoria("Algotimos Pŕatica", "DC5199", 2, new ArrayList<Disciplina>(), new DisciplinaObrigatoria());
        listaDisciplinas.put("DC5199",algoritmoPratica);
        Disciplina algoritmo = new DisciplinaObrigatoria("Algotimos", "DCC199", 4, new ArrayList<Disciplina>(), algoritmoPratica);
        listaDisciplinas.put("DCC199",algoritmo);
        Disciplina LICF = new DisciplinaObrigatoria("LICF", "FIS122", 2, new ArrayList<Disciplina>(),new DisciplinaObrigatoria() );
        listaDisciplinas.put("FIS122",LICF);
        Disciplina ICE = new DisciplinaObrigatoria("ICE", "ICE001", 2, new ArrayList<Disciplina>(), new DisciplinaObrigatoria());
        listaDisciplinas.put("ICE001",ICE);
        Disciplina Calculo1 = new DisciplinaObrigatoria("Calculo1", "MAT154", 2 ,new ArrayList<Disciplina>(), new DisciplinaObrigatoria());
        listaDisciplinas.put("MAT154",Calculo1);
        Disciplina GASL = new DisciplinaObrigatoria("GASL", "MAT155", 4, new ArrayList<Disciplina>(), new DisciplinaObrigatoria());
        listaDisciplinas.put("MAT155",GASL);
        Disciplina QuimicaF = new DisciplinaObrigatoria("Quimica Fundamental", "QUI125", 4, new ArrayList<Disciplina>(), new DisciplinaObrigatoria());
        listaDisciplinas.put("QUI125",QuimicaF);
        Disciplina LabQuim = new DisciplinaObrigatoria("Laboratória de Quimica", "QUI126", 2, new ArrayList<Disciplina>(), new DisciplinaObrigatoria());
        listaDisciplinas.put("QUI126",LabQuim);
        Disciplina AlgoritmoII = new DisciplinaObrigatoria("AlgoritmoII", "DCC200" , 4, List.of(algoritmo, algoritmo), new DisciplinaObrigatoria());
        listaDisciplinas.put("DCC200",AlgoritmoII);
        Disciplina AlgoritmoIIPratica = new DisciplinaObrigatoria("Algoritmo II Pratica ", "DC5200", 2, List.of(algoritmoPratica), AlgoritmoII);
        listaDisciplinas.put("DC5200",AlgoritmoIIPratica);
        Disciplina IntroEstatistica = new DisciplinaObrigatoria("Introdução à Estatística", "EST028", 4, List.of(Calculo1), new DisciplinaObrigatoria());
        listaDisciplinas.put("EST028",IntroEstatistica);
        Disciplina FisicaI = new DisciplinaObrigatoria("FisicaI", "FIS073", 4, List.of(Calculo1), new DisciplinaObrigatoria());
        listaDisciplinas.put("FIS073", FisicaI);
        Disciplina LabFisicaI = new DisciplinaObrigatoria("Laboratório de Fisica 1", "FIS077", 2, List.of(LICF), new DisciplinaObrigatoria());
        listaDisciplinas.put("FIS077", LabFisicaI);
        Disciplina CalculoII = new DisciplinaObrigatoria("CalculoII", "MAT156", 4, List.of(Calculo1, GASL), new DisciplinaObrigatoria());
        listaDisciplinas.put("MAT156", CalculoII);
        Disciplina LabQuimII = new DisciplinaObrigatoria("LabQuimII", "QUI168", 2, List.of(LabQuim), new DisciplinaObrigatoria());
        listaDisciplinas.put("QUI168",LabQuimII);
        Disciplina EstruturaDeDados = new DisciplinaObrigatoria("Estrutura de Dados", "DCC013", 4, List.of(AlgoritmoII), new DisciplinaObrigatoria());
        listaDisciplinas.put("DCC013", EstruturaDeDados);
        Disciplina OrientacaoObjetos = new DisciplinaObrigatoria("Orientação a objetos", "DCC025", 4, List.of(AlgoritmoII), new DisciplinaObrigatoria());
        listaDisciplinas.put("DCC025", OrientacaoObjetos);
        Disciplina CircuitosDigitais = new DisciplinaObrigatoria("Circuitos Digitais", "DCC122", 4, new ArrayList<Disciplina>(),new DisciplinaObrigatoria());
        listaDisciplinas.put("DCC122",CircuitosDigitais);
        Disciplina LogicaeFundComp = new DisciplinaObrigatoria("Logica e Fundamentos para a Computação", "DCC160", 4, new ArrayList<Disciplina>(),new DisciplinaObrigatoria());
        listaDisciplinas.put("DCC160", LogicaeFundComp);
        Disciplina ITN = new DisciplinaObrigatoria("Introdução a Teoria dos Números", "MAT143", 4, new ArrayList<Disciplina>(),new DisciplinaObrigatoria());
        listaDisciplinas.put("MAT143",ITN);
        Disciplina CalculoIII = new DisciplinaObrigatoria("CalculoIII", "MAT157", 4, List.of(CalculoII), new DisciplinaObrigatoria());
        listaDisciplinas.put("MAT157", CalculoIII);
        Disciplina WebDev = new DisciplinaObrigatoria("Desenvolvimento Web", "DCC202", 2, new ArrayList<Disciplina>(), new DisciplinaObrigatoria());
        listaDisciplinas.put("DCC202", WebDev);
        Disciplina CalculoNumerico = new DisciplinaObrigatoria("Cálculo Numérico", "DCC008", 4, List.of(algoritmo,CalculoII), new DisciplinaObrigatoria());
        listaDisciplinas.put("DCC008", CalculoNumerico);
        Disciplina EstruturadeDadosII = new DisciplinaObrigatoria("Estrutura de Dados II", "DCC012", 4, List.of(EstruturaDeDados), new DisciplinaObrigatoria());
        listaDisciplinas.put("DCC012", EstruturadeDadosII);
        Disciplina OrganizacaoComputadores = new DisciplinaObrigatoria("Organização de Computadores", "DCC070", 4, List.of(CircuitosDigitais), new DisciplinaObrigatoria());
        listaDisciplinas.put("DCC070", OrganizacaoComputadores);
        Disciplina ModelagemdeSistemas = new DisciplinaObrigatoria("Modelagem de Sistemas", "DCC177", 4, List.of(OrientacaoObjetos), new DisciplinaObrigatoria());
        listaDisciplinas.put("DCC177", ModelagemdeSistemas);
        Disciplina EquacoesDiferenciais = new DisciplinaObrigatoria("Equações Diferenciais I", "MAT029", 4, List.of(CalculoII), new DisciplinaObrigatoria());
        listaDisciplinas.put("MAT029",EquacoesDiferenciais);
        Disciplina AlgebraLinear = new DisciplinaObrigatoria("Álgebra Linear", "MAT158", 4, List.of(GASL), new DisciplinaObrigatoria());
        listaDisciplinas.put("MAT158", AlgebraLinear);
        Disciplina GameDev = new DisciplinaEletiva("Desenvolvimento de Jogos", "DCC148", 4, List.of(GASL, OrientacaoObjetos), new DisciplinaObrigatoria());
        listaDisciplinas.put("DCC148", GameDev);
        Disciplina InfonaEducacao = new DisciplinaEletiva("Informatica na Educação", "DCC086", 4, new ArrayList<Disciplina>(), new DisciplinaObrigatoria());
        listaDisciplinas.put("DCC086", InfonaEducacao);
        Disciplina VisuCientifica = new DisciplinaEletiva("Visualização Científica", "DCC191", 4, List.of(algoritmo, CalculoII), new DisciplinaObrigatoria());
        listaDisciplinas.put("DCC191", VisuCientifica);
        Disciplina TeoriadeFilas = new DisciplinaEletiva("Teoria de Filas", "DCC073", 4, List.of(IntroEstatistica), new DisciplinaObrigatoria());
        listaDisciplinas.put("DCC073", TeoriadeFilas);
        Disciplina FisicaII = new DisciplinaEletiva("Fisica II", "FIS074", 4, List.of(FisicaI), new DisciplinaObrigatoria());
        listaDisciplinas.put("FIS074", FisicaII);
        Disciplina InglesI = new DisciplinaOptativa("Lingua Inglesa Instrumental I", "UNI001", 4 , new ArrayList<Disciplina>(), new DisciplinaObrigatoria());
        listaDisciplinas.put("UNI001", InglesI);
        Disciplina LibrasI = new DisciplinaOptativa("LIbrais Intrumental I", "UNI015", 4 , new ArrayList<Disciplina>(), new DisciplinaObrigatoria());
        listaDisciplinas.put("UNI015", LibrasI);
        Disciplina InglesII = new DisciplinaOptativa("Lingua Inglesa Intrumental II", "UNI002", 4, List.of(LibrasI), new DisciplinaObrigatoria());
        listaDisciplinas.put("UNI002", InglesII);
        Disciplina LibrasII = new DisciplinaOptativa("LIbras Instrumental II", "UNI016", 4, List.of(LibrasI), new DisciplinaObrigatoria());
        listaDisciplinas.put("UNI016", LibrasII);
        Turma AlgA = new Turma("A",3,0,algoritmo, new Horario(List.of(SEGUNDA,QUINTA), 8));
        algoritmo.getTurmas().add(AlgA);
        Turma AlgB = new Turma("B", 3, 0 , algoritmo, new Horario(List.of(SEGUNDA,QUINTA),10));
        algoritmo.getTurmas().add(AlgB);
        Turma AlgC = new Turma("C", 3, 0, algoritmo, new Horario(List.of(SEGUNDA,QUINTA),14));
        algoritmo.getTurmas().add(AlgC);
        Turma licfA = new Turma("A", 3, 0, LICF, new Horario(List.of(SEGUNDA), 14));
        LICF.getTurmas().add(licfA);
        Turma licfB = new Turma("B",3,0,LICF, new Horario(List.of(QUARTA),14));
        LICF.getTurmas().add(licfB);
        Turma licfC = new Turma("C", 3, 0,LICF, new Horario(List.of(TERCA),10));
        LICF.getTurmas().add(licfC);
        Turma CalculoA = new Turma("A",3,0,Calculo1,new Horario(List.of(QUARTA,SEXTA),8));
        Calculo1.getTurmas().add(CalculoA);
        Turma CalculoB = new Turma("B", 3, 0, Calculo1, new Horario(List.of(QUARTA,SEXTA),10));
        Calculo1.getTurmas().add(CalculoB);
        Turma CalculoC = new Turma("C", 3, 0, Calculo1, new Horario(List.of(QUARTA,SEXTA),14));
        Calculo1.getTurmas().add(CalculoC);
        Turma QuimFundA = new Turma ("A", 3, 0, QuimicaF, new Horario(List.of(SEGUNDA,QUINTA),10));
        QuimicaF.getTurmas().add(QuimFundA);
        Turma QuimFundB = new Turma ("B", 3, 0, QuimicaF, new Horario(List.of(SEGUNDA,QUINTA),14));
        QuimicaF.getTurmas().add(QuimFundB);
        Turma QuimFundC = new Turma ("C", 3, 0, QuimicaF, new Horario(List.of(SEGUNDA,QUINTA),16));
        QuimicaF.getTurmas().add(QuimFundC);
        Turma AlgIIA = new Turma("A", 2, 0, AlgoritmoII, new Horario(List.of(QUARTA,SEXTA),16));
        AlgoritmoII.getTurmas().add(AlgIIA);
        Turma AlgIIB = new Turma("B", 3, 0 , AlgoritmoII, new Horario(List.of(QUARTA,SEXTA), 19));
        AlgoritmoII.getTurmas().add(AlgIIB);
        Turma AlgIIC = new Turma("C", 3, 0 , AlgoritmoII, new Horario(List.of(QUARTA,SEXTA), 21));
        AlgoritmoII.getTurmas().add(AlgIIC);
        Turma IntroEstatA = new Turma("A", 3, 0, IntroEstatistica, new Horario(List.of(TERCA, QUINTA), 10));
        IntroEstatistica.getTurmas().add(IntroEstatA);
        Turma IntroEstatB = new Turma("B", 2, 0, IntroEstatistica, new Horario(List.of(TERCA, QUINTA), 16));
        IntroEstatistica.getTurmas().add(IntroEstatB);
        Turma IntroEstatC = new Turma("C", 1, 0, IntroEstatistica, new Horario(List.of(TERCA, QUINTA), 19));
        IntroEstatistica.getTurmas().add(IntroEstatC);
        Turma LabFisica1A = new Turma("A", 3, 0, LabFisicaI, new Horario(List.of(SEGUNDA),16));
        LabFisicaI.getTurmas().add(LabFisica1A);
        Turma LabFisica1B = new Turma("B", 1, 0, LabFisicaI, new Horario(List.of(SEGUNDA),14));
        LabFisicaI.getTurmas().add(LabFisica1B);
        Turma LabFisica1C = new Turma("C", 2, 0, LabFisicaI, new Horario(List.of(QUINTA),14));
        LabFisicaI.getTurmas().add(LabFisica1C);
        Turma EDA = new Turma("A", 3,0, EstruturaDeDados, new Horario(List.of(QUARTA,SEXTA),14));
        EstruturaDeDados.getTurmas().add(EDA);
        Turma EDB = new Turma("B", 3,0, EstruturaDeDados, new Horario(List.of(QUARTA,SEXTA),16));
        EstruturaDeDados.getTurmas().add(EDB);
        Turma EDC = new Turma("C", 2, 0, EstruturaDeDados, new Horario(List.of(QUARTA,SEXTA), 19));
        EstruturaDeDados.getTurmas().add(EDC);
        Turma CircuitosDigA = new Turma("A", 2, 0, CircuitosDigitais, new Horario(List.of(TERCA,QUINTA), 16));
        CircuitosDigitais.getTurmas().add(CircuitosDigA);
        Turma CircuitosDigB = new Turma("B", 2, 0, CircuitosDigitais, new Horario(List.of(TERCA,QUINTA),19));
        CircuitosDigitais.getTurmas().add(CircuitosDigB);
        Turma CircuitosDigC = new Turma("C", 3, 0, CircuitosDigitais, new Horario(List.of(TERCA,QUINTA),21));
        CircuitosDigitais.getTurmas().add(CircuitosDigC);
        Turma ITNA = new Turma("A", 2, 0, ITN, new Horario(List.of(QUARTA, SEXTA), 10));
        ITN.getTurmas().add(ITNA);
        Turma ITNB = new Turma("B", 1, 0, ITN, new Horario(List.of(QUARTA, SEXTA), 8));
        ITN.getTurmas().add(ITNB);
        Turma ITNC = new Turma("C", 2, 0, ITN, new Horario(List.of(QUARTA, SEXTA), 14));
        ITN.getTurmas().add(ITNC);
        Turma WebDevA = new Turma("A", 3, 0, WebDev, new Horario(List.of(TERCA), 14));
        WebDev.getTurmas().add(WebDevA);
        Turma WebDevB = new Turma("B", 2, 0 , WebDev, new Horario(List.of(QUARTA), 14));
        WebDev.getTurmas().add(WebDevB);

    }
 }
